// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yivwylnrauqlmkxdzpoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpdnd5bG5yYXVxbG1reGR6cG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjgyOTAsImV4cCI6MjA3Mzc0NDI5MH0.YNeOZLYdRd8yh059U2FVLAnMeAjjxe7aJig9HlYDpL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});